export const affiliateSchemaSql = `
create table if not exists public.import_jobs (
  id bigint generated by default as identity primary key,
  source_file_id text unique not null,
  file_name text not null,
  source_type text not null,
  row_count integer default 0,
  status text not null default 'pending',
  imported_at timestamptz default now(),
  error_message text
);
create table if not exists public.affiliate_orders (
  id bigint generated by default as identity primary key,
  order_no text,
  click_id text,
  sub_id text,
  order_time timestamptz,
  click_time timestamptz,
  sales numeric default 0,
  commission numeric default 0,
  order_status text,
  attribution_type text,
  content_type text,
  raw jsonb,
  unique(order_no, click_id)
);
create table if not exists public.affiliate_clicks (
  id bigint generated by default as identity primary key,
  click_id text unique,
  click_time timestamptz,
  region text,
  sub_id text,
  referrer text,
  raw jsonb
);
create table if not exists public.daily_metrics (
  metric_date date primary key,
  sales numeric default 0,
  commission numeric default 0,
  orders integer default 0,
  clicks integer default 0,
  direct_commission numeric default 0,
  indirect_commission numeric default 0,
  d0_orders integer default 0,
  d0_cvr numeric default 0,
  commission_per_1k_clicks numeric default 0,
  updated_at timestamptz default now()
);
alter table public.import_jobs enable row level security;
alter table public.affiliate_orders enable row level security;
alter table public.affiliate_clicks enable row level security;
alter table public.daily_metrics enable row level security;
`;
