const API = "https://api.vercel.com";
function headers(){const token=process.env.VERCEL_TOKEN;if(!token)throw new Error("VERCEL_TOKEN is missing");return {Authorization:`Bearer ${token}`,"Content-Type":"application/json"};}
function teamQ(){return process.env.VERCEL_TEAM_ID?`?teamId=${encodeURIComponent(process.env.VERCEL_TEAM_ID)}`:"";}
export async function createVercelProject(name:string, githubRepo?:string){const body:any={name,framework:"nextjs"};if(githubRepo)body.gitRepository={type:"github",repo:githubRepo};const r=await fetch(`${API}/v10/projects${teamQ()}`,{method:"POST",headers:headers(),body:JSON.stringify(body)});if(!r.ok)throw new Error(`Vercel create project failed ${r.status}: ${await r.text()}`);const j:any=await r.json();return {id:j.id as string,name:j.name as string};}
export async function getVercelProject(idOrName:string){const r=await fetch(`${API}/v9/projects/${encodeURIComponent(idOrName)}${teamQ()}`,{headers:headers()});if(!r.ok)throw new Error(`Vercel get project failed ${r.status}: ${await r.text()}`);return await r.json();}
export async function setVercelEnv(projectId:string,key:string,value:string,target:("production"|"preview"|"development")[]=["production","preview","development"]){const suffix=teamQ();const r=await fetch(`${API}/v10/projects/${encodeURIComponent(projectId)}/env${suffix}`,{method:"POST",headers:headers(),body:JSON.stringify({key,value,type:"encrypted",target})});if(!r.ok){const t=await r.text();if(!t.includes("already exists"))throw new Error(`Vercel env failed ${r.status}: ${t}`);}return {key,target};}
export async function createDeployment(projectId:string,repoId:number,ref="main",name?:string){const body:any={project:projectId,target:"production",gitSource:{type:"github",repoId,ref}};if(name)body.name=name;const r=await fetch(`${API}/v13/deployments${teamQ()}`,{method:"POST",headers:headers(),body:JSON.stringify(body)});if(!r.ok)throw new Error(`Vercel deploy failed ${r.status}: ${await r.text()}`);return await r.json();}

export async function deleteVercelProject(idOrName:string){const r=await fetch(`${API}/v9/projects/${encodeURIComponent(idOrName)}${teamQ()}`,{method:"DELETE",headers:headers()});if(!r.ok&&r.status!==404)throw new Error(`Vercel delete project failed ${r.status}: ${await r.text()}`);return {deleted:true,project:idOrName};}
